---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_opcache_enable: "0"
    drush_launcher_install: false
    drush_composer_global_install: false
    drush_install_from_source: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: nholuong.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: nholuong.php-versions
    - role: nholuong.php
    - role: nholuong.composer
    - role: nholuong.git
    - role: nholuong.drush
